#!/bin/bash

#    Copyright 2012 Szymon Olewniczak
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.

COMMENT_PATH=/home/hafron/dev/disqus-from-cli/comment 
MAIL_PATH=/usr/bin/mail
LOG_FILE=/home/hafron/tmp/disqus.log
MAIL_TITLE="[Auto]Disqus comment result"
while read x
do
    if [[ "$x" =~ Subject:\ (.*) ]]; then
	url="${BASH_REMATCH[1]}"
    elif [[ "$x" =~ From\ ([^ ]*) ]]; then
	from="${BASH_REMATCH[1]}"
    elif [[ -z "$x" ]]; then
	break
    fi
done

while read x
do
    comm=$comm$x
done
echo "[`date`]" >> $LOG_FILE
echo "URL: $url" >> $LOG_FILE
echo "FROM: $from" >> $LOG_FILE
out="`$COMMENT_PATH -c "$comm" -u "$url"`"
echo "$out" >> $LOG_FILE
echo "" >> $LOG_FILE
echo "$out" | $MAIL_PATH -s "$MAIL_TITLE" $from
